#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# guardrails/setup.sh — Start the NeMo Guardrails proxy server
#
# Installs nemoguardrails (if missing), writes a config.yml from the current
# .workshop-env values, and starts the server on localhost:18090.
#
# Exposes: http://localhost:18090/v1/chat/completions (OpenAI-compatible)
# Stop:    bash guardrails/reset.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSHOP_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/config"
PID_FILE="/tmp/guardrails-proxy.pid"
LOG_FILE="/tmp/guardrails-proxy.log"
PORT=18090

info() { echo "[INFO]  $*"; }
ok()   { echo "[OK]    $*"; }
warn() { echo "[WARN]  $*"; }
fail() { echo "[FAIL]  $*" >&2; exit 1; }

# Load workshop environment
source "${WORKSHOP_ROOT}/.workshop-env" 2>/dev/null || \
  warn ".workshop-env not found — make sure MODEL_ENDPOINT and OPENAI_API_KEY are set."

MODEL_ENDPOINT="${MODEL_ENDPOINT:-https://openrouter.ai/api/v1}"
MODEL_NAME="${MODEL_NAME:-liquid/lfm-2.5-1.2b-instruct:free}"
OPENAI_API_KEY="${OPENAI_API_KEY:-${OPENROUTER_API_KEY:-}}"

# ── Step 1: Install nemoguardrails ──────────────────────────────────────────
info "Checking nemoguardrails installation..."
if ! python3 -c "import nemoguardrails" 2>/dev/null; then
  info "Installing nemoguardrails (this may take 30–60 s)..."
  uv pip install "nemoguardrails>=0.9" 2>&1 | tail -3
  ok "nemoguardrails installed."
else
  ok "nemoguardrails: $(python3 -c 'import nemoguardrails; print(nemoguardrails.__version__)' 2>/dev/null || echo 'installed')"
fi

# ── Step 2: Write config.yml from current environment ───────────────────────
info "Writing guardrails config for model: ${MODEL_NAME}"
cat > "${CONFIG_DIR}/config.yml" <<EOF
# NeMo Guardrails config — auto-generated by guardrails/setup.sh
# Edit guardrails/config/rails.co to change the Colang rules.

models:
  - type: main
    engine: openai
    model: ${MODEL_NAME}
    parameters:
      openai_api_base: ${MODEL_ENDPOINT}

rails:
  input:
    flows:
      - check pii input
      - check jailbreak
EOF
ok "Config written to ${CONFIG_DIR}/config.yml"

# ── Step 3: Stop any existing instance ──────────────────────────────────────
if [[ -f "${PID_FILE}" ]]; then
  OLD_PID=$(cat "${PID_FILE}" 2>/dev/null || echo "")
  [[ -n "${OLD_PID}" ]] && kill "${OLD_PID}" 2>/dev/null || true
  rm -f "${PID_FILE}"
fi
lsof -ti:"${PORT}" 2>/dev/null | xargs kill -9 2>/dev/null || true
sleep 1

# ── Step 4: Start NeMo Guardrails server ────────────────────────────────────
info "Starting NeMo Guardrails proxy on port ${PORT}..."
export OPENAI_API_KEY
export OPENAI_BASE_URL="${MODEL_ENDPOINT}"

nemoguardrails server \
  --config "${CONFIG_DIR}" \
  --port "${PORT}" \
  > "${LOG_FILE}" 2>&1 &

PROXY_PID=$!
echo "${PROXY_PID}" > "${PID_FILE}"

# ── Step 5: Wait for readiness ───────────────────────────────────────────────
for i in $(seq 1 15); do
  sleep 1
  if curl -sf "http://localhost:${PORT}/v1/models" >/dev/null 2>&1 || \
     curl -sf "http://localhost:${PORT}/health" >/dev/null 2>&1; then
    ok "NeMo Guardrails proxy ready at http://localhost:${PORT}/v1"
    break
  fi
  [[ "${i}" == "15" ]] && {
    warn "Server did not respond after 15 s. Check ${LOG_FILE}"
    warn "Try: curl http://localhost:${PORT}/v1/chat/completions"
  }
done

echo ""
echo "  Guarded endpoint: http://localhost:${PORT}/v1"
echo "  Bare endpoint:    ${MODEL_ENDPOINT}"
echo "  Log:              ${LOG_FILE}"
echo "  Stop:             bash guardrails/reset.sh"
echo ""
echo "  Rails active:"
echo "    ✦ PII Detection  — blocks messages sharing personal information"
echo "    ✦ Jailbreak Rail — blocks prompt-injection / instruction-override attempts"
echo ""
echo "  Test it:"
echo "    export GUARDED_ENDPOINT=http://localhost:${PORT}/v1"
echo ""
